title: Rocket Launch
hero_image: images/banner.png
description: Make an animation of a rocket
meta_title: Python coding projects for kids and teens | Rocket launch
meta_description: Learn Python with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Python animation that shows a rocket launching into orbit.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Step 1
  - title: Step 2
    completion:
      - engaged
  - title: Step 3
  - title: Step 4
  - title: Step 5
  - title: Step 6
  - title: Step 7
  - title: Step 8
  - title: Step 9
    completion:
      - internal
  - title: Step 10
    completion:
      - external
  - title: Step 11
  
