title: Rocket Launch
hero_image: images/banner.png
description: Make an animation of a rocket
meta_title: Python coding projects for kids and teens | Rocket launch
meta_description: Learn Python with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Python animation that shows a rocket launching into orbit.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Draw the background
  - title: Add a planet
    completion:
      - engaged
  - title: A different planet?
  - title: Load the rocket image
  - title: Draw the rocket
  - title: Blast off
  - title: Exhaust effects
  - title: Lots of circles
  - title: Random circles
    completion:
      - internal
  - title: Remove the outline
    completion:
      - external
  - title: What next?
  
