title: default-project-template
hero_image: images/banner.png
description: default-project-template description
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Draw the background
  - title: Add a planet
    completion:
      - engaged
  - title: A different planet?
  - title: Load the rocket image
  - title: Draw the rocket
    completion:
      - internal
  - title: Blast off
  - title: Exhaust effects
  - title: Lots of circles
  - title: Remove the outline
  - title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external

  
